### ISSUE TITLE
ru_RU.ini is empty

### ISSUE THREAD

**Issue by dmzkrsk** [heiglandreas/Org_Heigl_Hyphenator#20]
Russian locale doesn't work

**Comment by heiglandreas** [comment]
That might be. Do you have a hyphenation-file for russian?

**Comment by heiglandreas** [comment]
Strange.....

Might be an issue with UTF-8. I'll have to dig into that.

Will ping you tomorrow on that one!

**Comment by alkree** [comment]
Replace hyph_ru_RU.dic from here http://extensions.openoffice.org/en/project/slovari-dlya-russkogo-yazyka-dictionaries-russian and all will be fine.

**Comment by heiglandreas** [comment]
@alkree It already has been that hyphenation-dictionary. The issue was missing usage of multibyte-string methods to create the pattern-files. It's been fixed with #22
