### ISSUE TITLE
Missing dictionary for cs_CZ

### ISSUE THREAD

**Issue by hason** [heiglandreas/Org_Heigl_Hyphenator#27]

**Comment by heiglandreas** [comment]
AFAIK the last time I looked there wheren't czeck dictionaries available with OpenOffice. As their dictionaries are the base of the libs dictionaries I didn't include them. 

As I'm currently on holiday I'll see to it as soon as Inreturn to a decent internet connection. 

Should you find a dictionary I'd be more than happy for either a pulltequest or a hint to where to find them ;)

Cheers

**Comment by hason** [comment]
Yes, I have dic file, but how should I make ini file?

**Comment by heiglandreas** [comment]
I'm not sure currently. It's been a while since I wrote that. I'll have to dig through some code. Gimme a day please!

**Comment by heiglandreas** [comment]
Finally :simple_smile:

* Put the ```.dic``` file into the folder ```src/Org/Heigl/Hyphenator/share/files/dictionaries```.
* Take care that the filename of the ```.dic```-file starts with ```hyph```.
* Call ```php tools/renderDicts```

The last call should render all dictionaries into PHP-Files.

You might have to have a look at the ```renderDicts```-Script and adapt that. It basically calls the ```Dictionary::parseFile```-method.

I'd be absolutely happy when you could provide a PR at least with the dic-file in the appropriate folder. Please also quote the source of the file in the PR.

Thanks for your contribution!

**Comment by hason** [comment]
I have created PR #28.
