### ISSUE TITLE
No hyphenation for "rücke" (de-DE) found

### ISSUE THREAD

**Issue by crazyvonni** [heiglandreas/Org_Heigl_Hyphenator#36]
Hi,
I have an issue with the german dictionary (de_DE) in conjunction with "ü": 

I get no hyphenation for "rücke" (and derivations like "drücke", "Brücke"...) whereas"Röcke" (Rö-cke) and "räcke" (rä-cke) works fine. 

I use this settings: 

```
            $o->setHyphen($this->hyphSign)
                ->setDefaultLocale('de_DE')
                ->setRightMin(2)
                ->setLeftMin(2)
                ->setWordMin(3)
                ->setTokenizers('Whitespace', 'Punctuation');
```

Is this a bug or am I doing something wrong? 

Thanks
Vonni

**Comment by heiglandreas** [comment]
Hi Vonny!

Thanks for raising this. It should not be an issue. But I need to investigate a bit into it.

**Comment by heiglandreas** [comment]
From the underlying hyphenation patterns it absolutely makes sense that "Brücke" is not hyphenated but "Röcke" is. Though "Brücke" should be hyphenated as well, as [Der Duden](http://www.duden.de/rechtschreibung/Bruecke) states. I'll need to investigate whether the dictionary is missing stuff!

**Comment by heiglandreas** [comment]
When you set the hyphenation-quality  to ```Hyphenator::NORMAL``` like this it should work.

```php
 $o->setHyphen($this->hyphSign)
  ->setDefaultLocale('de_DE')
  ->setRightMin(2)
  ->setLeftMin(2)
  ->setWordMin(3)
  ->setQuality(Org_Heigl\Hyphenator\Hyphenator::NORMAL)
  ->setTokenizers('Whitespace', 'Punctuation');
```

**Comment by crazyvonni** [comment]
Hi Andreas,
thank you for the quick answer. 

Can you shortly explain, why this flag has such an remarkable effect - respectively what other effects are to be expected if I change the quality to "normal"?  What is the default quality? 

Thanks

**Comment by heiglandreas** [comment]
The default quality is ```Hyphenator::HIGHEST```. 

The thing is, that the hyphenation-dictionary includes patterns in different qualities. And higher qualities can overwrite lower ones. But usually a quality of ```Hyphenator::NORMAL``` is sufficient. The higher qualities add some additional exceptions from the default rules. And there is an exception to the rule to hyphenate before a ```cke``` and the end of the word when you use the highest quality (see [here](https://github.com/heiglandreas/Org_Heigl_Hyphenator/blob/master/src/share/files/dictionaries/de_DE.ini#L7227) - the 8 means to *not* hyphenate between ```ü``` and ```c```…)

So when you change the quality you might find that some hyphenations are done that probably shouldn't and others are skipped that should be done. But usually the higher the quality the more elaborate the exception to the rule is…

**Comment by crazyvonni** [comment]
> And there is an exception to the rule to hyphenate before a cke and the end of the word when you use the highest quality (see here - the 8 means to not hyphenate between ü and c…)

Are you sure, that this exception is correct? I cannot imagine any case for this.

Except of this problem everything has worked fine for me. For this reason, I am a little bit unhappy with changing the quality, which presumably causes diffrent (worser) results in other cases.

Would another way be to work with a local copy of "de_DE.ini" without this strange rule?

**Comment by heiglandreas** [comment]
That definitely would be an option! The only thing I can tell on whether that exception is correct or not is that it is included in the dic-files for german hyphenation that OpenOffice uses. As they are the basis of the hyphenation files I create for this hyphenator I have to assume that they are right… :-/

**Comment by heiglandreas** [comment]
And I just found the same pattern in the hyphenation-files for LibreOffice. See line 7259 in https://raw.githubusercontent.com/LibreOffice/dictionaries/master/de/hyph_de_DE.dic - so it seems to be a thing…

**Comment by crazyvonni** [comment]
Very strange...
