### ISSUE TITLE
Problems with composer installation in case insensitive file systems

### ISSUE THREAD

**Issue by bildschirmartist** [heiglandreas/Org_Heigl_Hyphenator#55]
Hi,
since version 2.5 of your library, I get problems when installing them via composer on my local Docker DEv environment (Docker Desktop 3.0.0 on a Windows 10).
The problem is caused by two files inside the `src/share/files/dictionaries/` folder, having the same filename but their file endings have a different spelling (uppercase vs. lowercase):
![image](https://user-images.githubusercontent.com/2776658/102863842-76146100-4433-11eb-9787-adc6ee77f6d1.png)

The problem could be resolved easily by removing either one of these files from the repository.

Thanks a lot and happy holidays.

**Comment by heiglandreas** [comment]
Hey. Thanks for bringing that to my attention! For the correct working of the library *both* files are irrelevant. But one licence should be enough. Even for brazilian portuguese 😁

I'll see to it to fix that and remove one of the two files. Expect a new release later today...
